# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SnCli < Formula
  desc "Cli tool to interact with the solarnetwork api"
  homepage "https://github.com/SolarNetwork/sn-cli"
  url "https://github.com/SolarNetwork/sn-cli/archive/refs/tags/0.17.0.tar.gz"
  version "0.17.0"
  sha256 "e8c66876256adf93e1ca8e1e81024bbc29b08b75de495dbfca0bba773cd0b0b0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.17.0/sn-cli-0.17.0-darwin-arm64.tar.gz"
      sha256 "146b3ca43073408eb00e1b773443bae9d52d77ee3fcc18a8936275669b3be824"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.17.0/sn-cli-0.17.0-linux-amd64.tar.gz"
      sha256 "4618c89bae892f970e463c767df9a7469add33ebb04e935518229792816c872b"
    end

    on_arm do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.17.0/sn-cli-0.17.0-linux-arm64.tar.gz"
      sha256 "54b92514b46b3fff7bb8f340f034895860686bf15c9e4904d08728428cc6307c"
    end
  end

  def install
    bin.install "s10k"
  end
end
