# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SnCli < Formula
  desc "Cli tool to interact with the solarnetwork api"
  homepage "https://github.com/SolarNetwork/sn-cli"
  url "https://github.com/SolarNetwork/sn-cli/archive/refs/tags/0.12.6.tar.gz"
  version "0.12.6"
  sha256 "126306a2237cd8d033136449fe70f54c2cf9555bd35c814bd2e9af3291bd03de"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.12.6/sn-cli-0.12.6-darwin-arm64.tar.gz"
      sha256 "d907c0f4a7c6b763f007748e1ae5c2614efe728a08407eb899c87f24744be70c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.12.6/sn-cli-0.12.6-linux-amd64.tar.gz"
      sha256 "45afd4c883af5e7c0fd19322e6167a996c4c938ef604c86f1790be6c4497005c"
    end

    on_arm do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.12.6/sn-cli-0.12.6-linux-arm64.tar.gz"
      sha256 "96dcd4ba93bb148e3391186842e566592dd0d6b02189fa2a54a25763651c10b7"
    end
  end

  def install
    bin.install "s10k"
  end
end
