# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SnCli < Formula
  desc "Cli tool to interact with the solarnetwork api"
  homepage "https://github.com/SolarNetwork/sn-cli"
  url "https://github.com/SolarNetwork/sn-cli/archive/refs/tags/0.12.4.tar.gz"
  sha256 "b8477b8bb7b453ad16b9d2203b48c292ac592a3a2078c3db12da47046ece11fa"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.12.4/sn-cli-0.12.4-darwin-arm64.tar.gz"
      sha256 "ef18c51960dd2e7300541605550a14b5415c5b2a5d89e8f593771c34c5e77fa3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.12.4/sn-cli-0.12.4-linux-amd64.tar.gz"
      sha256 "469063486640b3f3bdcd3722c0c5fedc6ed289b6612bad0dfa7647cb9d5d7a64"
    end

    on_arm do
      url "https://github.com/SolarNetwork/sn-cli/releases/download/0.12.4/sn-cli-0.12.4-linux-arm64.tar.gz"
      sha256 "d3d554bce5497543777919f34d70089becafd286bdb2a584092533e0689c1e3e"
    end
  end

  def install
    prefix.install Dir["*"]
  end
end
